### ISSUE TITLE
several warnings from startup

### ISSUE THREAD

**Issue by Pepan** [wedesoft/hornetseye-rmagick#1]
/home/pepa/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/x86_64-linux/continuation.so: warning: callcc is obsolete; use Fiber instead
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead

**Comment by wedesoft** [comment]
I just fixed the "rmagick" one (hornetseye-rmagick version 1.0.4). Not sure how "callcc" is called here. I need to try Ruby 2.2.0 when I find time for it.

**Comment by Pepan** [comment]
Warning disappeared! Thank you!

**Comment by wedesoft** [comment]
Ok, thanks for letting me know.
